### ISSUE TITLE
Can't start - error occurs during run under Windows

### ISSUE THREAD

**Issue by AngelTs** [yownas/lcm-webui#2]
(venv) C:\lcm-webui-main>python webui.py

C:\lcm-webui-main\venv\lib\site-packages\huggingface_hub\file_download.py:659: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'
  warnings.warn(
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [00:01<00:00,  3.73it/s]
Traceback (most recent call last):
  File "C:\lcm-webui-main\webui.py", line 205, in <module>
    block.load(_js=scripts)
TypeError: EventListener._setup.<locals>.event_trigger() got an unexpected keyword argument '_js'

(venv) C:\lcm-webui-main>

**Comment by yownas** [comment]
Oh. Sorry. I think I know what happen. Gradio v4 was just released, and since I didn't specify which version I wanted it would install a newer one that has changes that break things for me.

I've updated requirements.txt to use a tested version of gradio, so if you do a `git pull` of just get the new file you should be able to run `pip install -r requirements.txt` again and it will downgrade to a good version.

**Comment by AngelTs** [comment]
Thank you, now it is working!
Do you know how to overcome the NSFW restriction here?
 "Potential NSFW content was detected in one or more images. A black image will be returned instead."

**Comment by yownas** [comment]
The nsfw-check was built into the pipeline so I didn't want to mess with it too much.

...that said, there might be a `--naughty` option. :)

**Comment by AngelTs** [comment]
> The nsfw-check was built into the pipeline so I didn't want to mess with it too much.
> 
> ...that said, there might be a `--naughty` option. :)

Perfect.Thanks
